// This file is automatically generated by internal/scripts/refresh-assets.ts in
// upstream tldraw. Vendored verbatim for the Svelte port.
// Do not edit manually.

export const version = '5.0.1'
export const publishDates = {
	major: '2026-05-06T16:28:18.473Z',
	minor: '2026-05-06T16:28:18.473Z',
	patch: '2026-05-15T17:02:50.276Z',
}
